### ISSUE TITLE
Just to say hi...

### ISSUE THREAD

**Issue by variable** [geekitude/dokuwiki-plugin-userhomepage#33]
Hey, original plugin creator here ... :)
I was googling myself and the plugin page came up, and holy shit it's still being maintained, good work!

**Comment by geekitude** [comment]
Hi

Thanks for stopping by and for saying hello ;)
I hope there's no problem about the plugin, let me know if you want me to
change anything.

Have a Nice day

Le 30 janv. 2018 11:22 AM, "James Lin" <notifications@github.com> a écrit :

Hey, original plugin creator here ... :)
I was googling myself and the plugin page came up, and holy shit it's still
being maintained, good work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/geekitude/dokuwiki-plugin-userhomepage/issues/33>, or mute
the thread
