### ISSUE TITLE
User icon outdated

### ISSUE THREAD

**Issue by L--U--P--U--S** [geekitude/dokuwiki-plugin-userhomepage#46]
Hi,

with Dokuwiki version "Igor", many icons/images have been replaced by new svg counterparts. This extension comes with its own icons `user.png` and `ns.png` (stored in `/lib/plugins/userhomepage/images`), which are copies(?) of the icons used by the previous Dokuwiki version "Hogfather".

In Hogfather, the user icons, as used for interwiki links to userhomepages, the top right "logged in as …" text or the "last modified" text on the bottom right below the actual page content, are all the same: 
![grafik](https://user-images.githubusercontent.com/1579186/186172106-563b9153-8a5c-42f2-b815-f6633b6a238d.png)

On the contrary, in Igor, the "logged in as …" text, which is altered by this plugin, still uses the old user icon from the plugin directory and therefore looks quite different compared to the new default user icon:
![grafik](https://user-images.githubusercontent.com/1579186/186179571-db3f4bd5-a150-46fd-81fe-166104d93915.png)

I have a suggestion to fix this problem: Why not use the images shipped with Dokuwiki - meaning - which are always available anyway? The `ns.png` file is available in `/lib/images` and the new `user.svg` is available in `/lib/images/interwiki`. Could this be possible?

Additional info: I am using Dokuwiki's default template.

----

UPDATE: I just commented out [line 7 in style.css](https://github.com/geekitude/dokuwiki-plugin-userhomepage/blob/f5d0519d7e7075349ab218cd54f95a7784c02cbf/style.css#L7), which seems to force Dokuwiki to use the default icon. I guess the same is true for line 6. Problem solved for the time being.

I still want to raise the question, if this could be a permanent change for this extension? Two lines less to maintain, two image files less to provide …

**Comment by geekitude** [comment]
Hi

Thanks for pointing that out and for the solution you proposed.
It will try to fix it within as soon as possible.

Simon

Le mar. 23 août 2022, 16:10, Thomas Wolf ***@***.***> a
écrit :

**Comment by geekitude** [comment]
Hello

It could become a source of problem to use both png and svg images (one having a scaling capacity while the other doesn't) so I had to use svg images for both.

Selected one for private namespace since Dokuwiki has none that could match (from https://materialdesignicons.com/ wich I think is the source used for Dokuwiki's svg). On top of that, I had to keep old images as default for outdated Dokuwikis out there.

So Userhomepage still doesn't use images provided by Dokuwiki but you can now choose between png or svg style with new setting named `userlink_icons`.

Regards,
Simon
